---
title: "README"
output: html_document
---

O objetivo da ferramenta é acrescentar à planilha de controle existente, a nova demanda recebida, sinalizando duplicidades, quando houver.

Resumo: Atualiza a planilha de controle e gera uma mensagem, caso seja necessário, sinalizando duplicidade de solicitação de elementar (verifica se na planilha de controle o elementar já havia sido solicitado e retorna o número da CI onde ele foi solicitado – coluna A: Origem). Caso a coluna de elementar esteja vazia, realiza essa verificação através do Item externo e, em casos em que ambos estejam vazias, sinaliza que a planilha não tem o elementar e o externo.


## Como utilizar a ferramenta?
0. Atualizar a pasta ‘INPUT’ com as novas demandas recebidas (extraída do sistema de Cis)

1. Abrir o arquivo ‘Projeto.R’

2. Aguardar inicialização do RStudio (IDE)

3. Rodar o script ‘Run.R’

4. Aguardar a mensagem: “Planilha gerada com sucesso!”

5. Fechar o projeto no RStudio (don’t save!)


## Dependências
R version 4.2.1 (2022-06-23 ucrt)

Platform: x86_64-w64-mingw32/x64 (64-bit)

Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:

[1] LC_COLLATE=Portuguese_Brazil.utf8

[2] LC_CTYPE=Portuguese_Brazil.utf8

[3] LC_MONETARY=Portuguese_Brazil.utf8

[4] LC_NUMERIC=C

[5] LC_TIME=Portuguese_Brazil.utf8

attached base packages:

[1] stats graphics grDevices utils datasets methods

[7] base

loaded via a namespace (and not attached):

[1] rstudioapi_0.14 magrittr_2.0.3 tidyselect_1.1.2

[4] R6_2.5.1 rlang_1.0.5 fansi_1.0.3

[7] stringr_1.4.1 dplyr_1.0.10 tools_4.2.1

[10] utf8_1.2.2 cli_3.4.1 DBI_1.1.3

[13] ellipsis_0.3.2 readxl_1.4.1 assertthat_0.2.1

[16] tibble_3.1.8 lifecycle_1.0.2 purrr_0.3.4

[19] vctrs_0.4.1 glue_1.6.2 stringi_1.7.8

[22] compiler_4.2.1 pillar_1.8.1 cellranger_1.1.0

[25] generics_0.1.3 writexl_1.4.0 lubridate_1.8.0

[28] pkgconfig_2.0.3